"""Add search_vector column for full-text search

Revision ID: 375c3cdd70b8
Revises: 40ee3934cf27
Create Date: 2025-09-15 22:01:50.921406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '375c3cdd70b8'
down_revision: Union[str, Sequence[str], None] = '40ee3934cf27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    
    # Create GIN index for fast full-text search
    op.create_index('papers_search_vector_idx', 'papers', ['search_vector'], postgresql_using='gin')
    
    # Populate search_vector for existing records
    op.execute("""
        UPDATE papers SET search_vector = 
            setweight(to_tsvector('english', title), 'A') ||
            setweight(to_tsvector('english', abstract), 'B') ||
            setweight(to_tsvector('english', full_text), 'C')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('papers_search_vector_idx', table_name='papers')
    op.drop_column('papers', 'search_vector')
    # ### end Alembic commands ###
